(()=>{'use strict';
const KEY='rishu_erp_v11';
const LEGACY=['rishu_erp_v9','rishu_erp_v8','rishu_erp_v7','rishu_erp_v6','rishu_erp_v5','rishu_erp_v4','rishu_erp_v3','rishu_erp_v2','rishu_erp','rishu_medical_erp','rishu_medical_erp_v2','rishu_medical_erp_v3','rishu_medical_erp_v4'];
const GST=[0,2.5,5,12,18,28];
const UNITS=['Tablet','Capsule','Bottle','Tube','Box','Piece','Strip'];
const empty={items:[],parties:[],sales:[],purchases:[],returns:[],doctors:[],expenses:[],purchaseOrders:[],payments:[],users:[{id:'u_admin',name:'Administrator',username:'admin',password:'admin123',role:'Admin',active:true}]};
let db=loadDB(), saleRows=[], purchaseRows=[], modalReturn='item', editingIndex=-1;
const $=id=>document.getElementById(id);
function raw(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function money(v){return '₹'+num(v).toFixed(2)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function today(){return new Date().toISOString().slice(0,10)}
function normalizeItem(i={}){return {id:i.id||cryptoRandom(),product:String(i.product||''),barcode:String(i.barcode||''),company:String(i.company||''),salt:String(i.salt||''),hsn:String(i.hsn||''),unit:String(i.unit||'Tablet'),batch:String(i.batch||''),exp:String(i.exp||i.expiry||''),pack:Math.max(1,num(i.pack)||1),mrp:num(i.mrp),rate:num(i.rate??i.prate),gst:num(i.gst),stock:Math.max(0,num(i.stock)),rack:String(i.rack||''),reorder:Math.max(0,num(i.reorder)||10)}}
function normalizeParty(p={}){return {id:p.id||cryptoRandom(),name:String(p.name||''),type:p.type==='Supplier'?'Supplier':'Customer',mobile:String(p.mobile||''),gstin:String(p.gstin||''),address:String(p.address||''),creditLimit:num(p.creditLimit)}}
function cryptoRandom(){return 'id_'+Math.random().toString(36).slice(2)+Date.now().toString(36)}
function normalizeDoctor(x={}){return {id:x.id||cryptoRandom(),name:String(x.name||''),specialization:String(x.specialization||''),mobile:String(x.mobile||''),clinic:String(x.clinic||''),reg:String(x.reg||'')}}
function norm(d){d=d||{};return {items:Array.isArray(d.items)?d.items.map(normalizeItem):[],parties:Array.isArray(d.parties)?d.parties.map(normalizeParty):[],sales:Array.isArray(d.sales)?d.sales:[],purchases:Array.isArray(d.purchases)?d.purchases:[],returns:Array.isArray(d.returns)?d.returns:[],doctors:Array.isArray(d.doctors)?d.doctors.map(normalizeDoctor):[],expenses:Array.isArray(d.expenses)?d.expenses:[],purchaseOrders:Array.isArray(d.purchaseOrders)?d.purchaseOrders:[],payments:Array.isArray(d.payments)?d.payments:[],users:Array.isArray(d.users)&&d.users.length?d.users:empty.users};}
function merge(a,b){const ik=new Set(a.items.map(x=>(x.product+'|'+x.batch).toLowerCase()));b.items.forEach(x=>{const k=(x.product+'|'+x.batch).toLowerCase();if(x.product&&!ik.has(k)){a.items.push(x);ik.add(k)}});const pk=new Set(a.parties.map(x=>(x.name+'|'+x.type).toLowerCase()));b.parties.forEach(x=>{const k=(x.name+'|'+x.type).toLowerCase();if(x.name&&!pk.has(k)){a.parties.push(x);pk.add(k)}});for(const key of ['sales','purchases','returns','expenses','purchaseOrders','payments']){const s=new Set(a[key].map(x=>String(x.no||x.id||'')));b[key].forEach(x=>{const k=String(x.no||x.id||'');if(k&&!s.has(k)){a[key].push(x);s.add(k)}})}}
function loadDB(){let d=norm(raw(KEY)||empty);LEGACY.forEach(k=>{const x=raw(k);if(x)merge(d,norm(x.data||x))});return d}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));localStorage.setItem('rishu_erp_auto_backup',JSON.stringify({app:'RISHU MEDICAL AND HEALTHCARE ERP',version:12,updatedAt:new Date().toISOString(),data:db}));if(window.cloudBridge)window.cloudBridge.scheduleSync(db)}catch(e){alert('Data save nahi ho saka. Browser storage full/blocked hai. Backup download karke rakhein.')}}
function shop(){return {name:localStorage.getItem('rishu_shop_name')||'RISHU MEDICAL AND HEALTHCARE',mobile:localStorage.getItem('rishu_shop_mobile')||'9983052105',address:localStorage.getItem('rishu_shop_address')||'Bhalni, District Jalore, Rajasthan'}}
function layout(title,action=''){return `<div class="title"><h2>${title}</h2><div>${action}</div></div>`}
function show(page){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));(pages[page]||dashboard)();window.scrollTo(0,0)}
function clock(){if($('clock'))$('clock').textContent=new Date().toLocaleString('en-IN',{dateStyle:'short',timeStyle:'medium'})}setInterval(clock,1000);clock();
$('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(b)show(b.dataset.page)});
function dashboard(){const d=today(),sales=db.sales.filter(x=>String(x.date||'').slice(0,10)===d),saleTotal=sales.reduce((a,x)=>a+num(x.net),0),low=db.items.filter(x=>num(x.stock)<=num(x.reorder)),exp=nearExpiryCount();$('app').innerHTML=layout('Dashboard',`<button class="btn" onclick="show('sale')">F2 • New Sale</button>`)+`<div class="grid"><div class="stat"><small>Today's Sale</small><b>${money(saleTotal)}</b></div><div class="stat"><small>Total Sale Bills</small><b>${db.sales.length}</b></div><div class="stat"><small>Items / Batches</small><b>${db.items.length}</b></div><div class="stat"><small>Low Stock</small><b>${low.length}</b></div></div><div class="grid"><div class="stat"><small>Purchase Bills</small><b>${db.purchases.length}</b></div><div class="stat"><small>Near Expiry</small><b>${exp}</b></div><div class="stat"><small>Customers</small><b>${db.parties.filter(p=>p.type==='Customer').length}</b></div><div class="stat"><small>Suppliers</small><b>${db.parties.filter(p=>p.type==='Supplier').length}</b></div></div><div class="card"><h3>Quick Menu</h3><div class="actions"><button class="btn" onclick="show('sale')">🧾 Retail Sale</button><button class="btn gray" onclick="show('purchase')">🛒 Purchase</button><button class="btn gray" onclick="partyModal('Customer','dashboard')">👤 New Customer</button><button class="btn gray" onclick="partyModal('Supplier','dashboard')">🏢 New Supplier</button><button class="btn gray" onclick="itemModal('dashboard')">💊 New Item / Batch</button><button class="btn gray" onclick="show('stock')">📦 Stock</button><button class="btn gray" onclick="show('reports')">📊 Reports</button><button class="btn gray" onclick="show('backup')">💾 Backup</button></div></div><div class="card"><h3>Alerts</h3>${low.slice(0,20).map(x=>`<div class="danger">⚠ ${esc(x.product)} • Batch ${esc(x.batch)} • Stock ${x.stock} units • Rack ${esc(x.rack||'-')}</div>`).join('')||'<div class="muted">No low-stock alerts.</div>'}</div>`}
function partyOpts(type,selected=''){let h=`<option value="">Select ${type}</option>`;return h+db.parties.filter(p=>p.type===type).map(p=>`<option value="${esc(p.name)}" ${p.name===selected?'selected':''}>${esc(p.name)}${p.mobile?' • '+esc(p.mobile):''}</option>`).join('')}
function sale(){saleRows=[];$('app').innerHTML=layout('Retail Sale / Billing',`<button class="btn" onclick="newSale()">F2 • New Sale</button>`)+`<div class="note"><b>Retail/MARG-style sale:</b> MRP tax-inclusive • Batch-wise • Strip + Loose • 0%, 2.5%, 5%, 12%, 18%, 28% GST • FEFO-ready search • Automatic stock deduction.</div><div class="card"><h3>Bill Header</h3><div class="formgrid"><div class="field wide"><label>Medicine / Barcode / Batch</label><input id="saleSearch" placeholder="Type name/barcode/batch and press Enter" autocomplete="off"><div id="saleSuggestions" class="suggestions"></div></div><div class="field"><label>Party</label><select id="saleParty">${partyOpts('Customer')}</select></div><div class="field"><label>Mobile</label><input id="saleMobile"></div><div class="field"><label>Doctor / Prescriber</label><select id="saleDoctor">${doctorOpts()}</select></div><div class="field"><label>Prescription / Rx No.</label><input id="saleRx" placeholder="Optional"></div><div class="field"><label>Payment</label><select id="salePay"><option>Cash</option><option>UPI</option><option>Card</option><option>Credit</option></select></div><div class="field"><label>GST Mode</label><select id="saleGst"><option value="local">Local • CGST + SGST</option><option value="inter">Interstate • IGST</option></select></div><div class="field"><label>Bill Discount ₹</label><input id="saleDiscount" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>Received ₹</label><input id="saleReceived" type="number" min="0" step="0.01" value="0"></div></div><div class="actions"><button class="btn gray" onclick="partyModal('Customer','sale')">+ New Customer</button><button class="btn gray" onclick="itemModal('sale')">+ New Item / Batch</button></div></div><div class="card"><h3>Sale Items • Batch • Strip / Loose</h3><div class="scroll"><table><thead><tr><th>#</th><th>Product</th><th>Batch</th><th>Exp</th><th>Pack</th><th>Strip Qty</th><th>Loose</th><th>Total Units</th><th>MRP/Strip</th><th>GST</th><th>Disc%</th><th>Amount</th><th></th></tr></thead><tbody id="saleBody"></tbody></table></div></div><div id="saleTotals"></div>`;const s=$('saleSearch');s.oninput=()=>suggest('sale');s.onfocus=()=>suggest('sale');s.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addSaleSearch()}};$('saleParty').onchange=()=>fillParty('sale');['saleDiscount','saleReceived','saleGst'].forEach(id=>$(id).addEventListener('input',renderSale));$('saleGst').onchange=renderSale;renderSale();s.focus()}
function newSale(){sale()}
function fillParty(t){const p=db.parties.find(x=>x.name===$(t==='sale'?'saleParty':'pSupplier').value);if(p&&t==='sale')$('saleMobile').value=p.mobile||''}
function matches(q){q=(q||'').trim().toLowerCase();let a=db.items;if(q)a=a.filter(i=>(i.product+' '+i.batch+' '+i.barcode+' '+i.company+' '+i.salt+' '+i.hsn).toLowerCase().includes(q));return a.sort((a,b)=>String(a.exp).localeCompare(String(b.exp))).slice(0,20)}
function suggest(type){const inp=$(type==='sale'?'saleSearch':'pSearch'),box=$(type==='sale'?'saleSuggestions':'pSuggestions');if(!inp||!box)return;const arr=matches(inp.value);box.innerHTML=arr.map(x=>`<button class="suggestion" type="button" onclick="chooseItem('${type}','${esc(x.id)}')"><b>${esc(x.product)}</b> • Batch ${esc(x.batch)} • Exp ${esc(x.exp||'-')} • MRP ${money(x.mrp)} • Stock ${x.stock}</button>`).join('')||'<div class="empty">No item found. Use + New Item / Batch.</div>'}
function chooseItem(type,id){const x=db.items.find(i=>i.id===id);if(!x)return;if(type==='sale'){saleRows.push({...x,stripQty:1,looseQty:0,discount:0});$('saleSearch').value='';$('saleSuggestions').innerHTML='';renderSale()}else{purchaseRows.push({...x,pqty:1,freeQty:0,prate:num(x.rate),pdisc:0});$('pSearch').value='';$('pSuggestions').innerHTML='';renderPurchase()}}
function addSaleSearch(){const q=$('saleSearch').value.trim();if(!q)return;const x=db.items.find(i=>i.product.toLowerCase()===q.toLowerCase()||i.barcode.toLowerCase()===q.toLowerCase()||i.batch.toLowerCase()===q.toLowerCase())||matches(q)[0];if(!x)return alert('Item not found. Create item/batch first.');if(num(x.stock)<=0)return alert('Stock zero: '+x.product+' / '+x.batch);saleRows.push({...x,stripQty:1,looseQty:0,discount:0});$('saleSearch').value='';$('saleSuggestions').innerHTML='';renderSale()}
function saleCalc(){let subtotal=0,itemDiscount=0;const lines=saleRows.map(r=>{const pack=Math.max(1,num(r.pack)||1),strip=Math.max(0,num(r.stripQty)),loose=Math.max(0,num(r.looseQty)),qty=strip*pack+loose,gross=(num(r.mrp)/pack)*qty,disc=gross*Math.min(100,Math.max(0,num(r.discount)))/100,after=Math.max(0,gross-disc);subtotal+=gross;itemDiscount+=disc;return {...r,pack,stripQty:strip,looseQty:loose,qty,gross,itemDiscount:disc,after}});const itemNet=lines.reduce((a,x)=>a+x.after,0),billDisc=Math.min(itemNet,Math.max(0,num($('saleDiscount')?.value))),final=lines.map(x=>{const base=Math.max(0,x.after-(itemNet?billDisc*x.after/itemNet:0)),rate=num(x.gst),tax=base*rate/(100+rate);return {...x,base,taxable:base-tax,tax}});const taxable=final.reduce((a,x)=>a+x.taxable,0),tax=final.reduce((a,x)=>a+x.tax,0),net=taxable+tax,received=Math.max(0,num($('saleReceived')?.value)),change=Math.max(0,received-net);return{lines:final,subtotal,itemDiscount,billDisc,taxable,tax,net,received,change}}
function renderSale(){const body=$('saleBody');if(!body)return;const c=saleCalc();body.innerHTML=c.lines.map((r,i)=>`<tr><td>${i+1}</td><td><b>${esc(r.product)}</b></td><td>${esc(r.batch)}</td><td>${esc(r.exp)}</td><td>${r.pack}</td><td><input type="number" min="0" value="${r.stripQty}" onchange="saleRows[${i}].stripQty=this.value;renderSale()"></td><td><input type="number" min="0" value="${r.looseQty}" onchange="saleRows[${i}].looseQty=this.value;renderSale()"></td><td>${r.qty}</td><td>${money(r.mrp)}</td><td>${r.gst}%</td><td><input type="number" min="0" max="100" step="0.01" value="${r.discount}" onchange="saleRows[${i}].discount=this.value;renderSale()"></td><td>${money(r.after+r.tax)}</td><td><button class="btn red" onclick="saleRows.splice(${i},1);renderSale()">×</button></td></tr>`).join('')||'<tr><td colspan="13" class="muted">No items. Search an item or create a new batch.</td></tr>';const inter=$('saleGst')?.value==='inter';$('saleTotals').innerHTML=`<div class="totalbox"><div class="totalrow"><span>Subtotal</span><b>${money(c.subtotal)}</b></div><div class="totalrow"><span>Item Discount</span><b>${money(c.itemDiscount)}</b></div><div class="totalrow"><span>Bill Discount</span><b>${money(c.billDisc)}</b></div><div class="totalrow"><span>Taxable</span><b>${money(c.taxable)}</b></div><div class="totalrow"><span>${inter?'IGST':'CGST + SGST'}</span><b>${money(c.tax)}</b></div><div class="totalrow net"><span>NET PAYABLE</span><b>${money(c.net)}</b></div><div class="totalrow"><span>Received</span><b>${money(c.received)}</b></div><div class="totalrow"><span>Change</span><b>${money(c.change)}</b></div><div class="actions"><button class="btn green" onclick="saveSale()">💾 Save & Print Bill</button><button class="btn" onclick="previewSale()">🖨 Preview</button><button class="btn gray" onclick="newSale()">Clear</button></div></div>`}
function saveSale(){const c=saleCalc();if(!c.lines.length)return alert('Add at least one item.');for(const l of c.lines){const it=db.items.find(i=>i.id===l.id);if(!it||num(it.stock)<l.qty)return alert(`Insufficient stock: ${l.product} / ${l.batch}. Available ${it?it.stock:0} units.`)}const no='S'+(1001+db.sales.length),b={no,date:new Date().toLocaleString('en-IN'),party:$('saleParty').value||'Cash Customer',mobile:$('saleMobile').value,doctor:$('saleDoctor').value,rx:$('saleRx').value,payment:$('salePay').value,mode:$('saleGst').value,subtotal:c.subtotal,itemDiscount:c.itemDiscount,billDiscount:c.billDisc,discount:c.itemDiscount+c.billDisc,taxable:c.taxable,tax:c.tax,net:c.net,received:c.received,change:c.change,lines:c.lines};c.lines.forEach(l=>{const it=db.items.find(i=>i.id===l.id);it.stock=Math.max(0,num(it.stock)-l.qty)});db.sales.push(b);save();alert('Sale saved: '+no);printSale(b)}
function purchase(){purchaseRows=[];$('app').innerHTML=layout('Purchase Bill',`<button class="btn" onclick="newPurchase()">F8 • New Purchase</button>`)+`<div class="note"><b>MARG-style Purchase Entry:</b> Supplier → Invoice → Item/Batch → Pack → Qty → Free → Scheme/Discount → Purchase Rate → MRP → GST → Stock. Purchase rate is GST-exclusive. Saving purchase automatically creates/updates the exact Product + Batch stock.</div><div class="card"><h3>Purchase Header</h3><div class="formgrid"><div class="field"><label>Supplier *</label><select id="pSupplier">${partyOpts('Supplier')}</select></div><div class="field"><label>Invoice No. *</label><input id="pInvoice" value="P${1001+db.purchases.length}"></div><div class="field"><label>Invoice Date</label><input id="pDate" type="date" value="${today()}"></div><div class="field"><label>Payment</label><select id="pPay"><option>Credit</option><option>Cash</option><option>UPI</option><option>Card</option></select></div><div class="field"><label>GST Mode</label><select id="pGst"><option value="local">Local • CGST + SGST</option><option value="inter">Interstate • IGST</option></select></div><div class="field"><label>Bill Discount ₹</label><input id="pDiscount" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>Paid ₹</label><input id="pPaid" type="number" min="0" step="0.01" value="0"></div><div class="field"><label>Round Off ₹</label><input id="pRound" type="number" step="0.01" value="0"></div><div class="field wide"><label>Item / Barcode / Batch</label><input id="pSearch" placeholder="Search item/barcode/batch and press Enter" autocomplete="off"><div id="pSuggestions" class="suggestions"></div></div></div><div class="actions"><button class="btn" onclick="addPurchaseSearch()">+ Add Item</button><button class="btn gray" onclick="itemModal('purchase')">+ New Item / Batch</button><button class="btn gray" onclick="partyModal('Supplier','purchase')">+ New Supplier</button><button class="btn gray" onclick="addBlankPurchase()">+ Blank Line</button></div></div><div class="card"><h3>Purchase Items • Batch • Scheme • Rate • MRP</h3><div class="scroll"><table><thead><tr><th>#</th><th>Product</th><th>Batch</th><th>Expiry</th><th>Pack</th><th>Qty</th><th>Free</th><th>Scheme%</th><th>Purchase Rate/Strip</th><th>MRP/Strip</th><th>GST</th><th>Amount</th><th></th></tr></thead><tbody id="pBody"></tbody></table></div></div><div id="pTotals"></div>`;const s=$('pSearch');s.oninput=()=>suggest('purchase');s.onfocus=()=>suggest('purchase');s.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addPurchaseSearch()}};['pDiscount','pPaid','pRound','pGst'].forEach(id=>$(id).addEventListener('input',renderPurchase));$('pGst').onchange=renderPurchase;renderPurchase();s.focus()}
function newPurchase(){purchase()}
function addPurchaseSearch(){const q=$('pSearch').value.trim();if(!q)return;const x=db.items.find(i=>i.product.toLowerCase()===q.toLowerCase()||i.barcode.toLowerCase()===q.toLowerCase()||i.batch.toLowerCase()===q.toLowerCase())||matches(q)[0];if(!x)return alert('Item not found. Use + New Item / Batch or + Blank Line.');purchaseRows.push({...x,pqty:1,freeQty:0,prate:num(x.rate),pdisc:0});$('pSearch').value='';$('pSuggestions').innerHTML='';renderPurchase()}
function addBlankPurchase(){purchaseRows.push(normalizeItem({product:'',batch:'',exp:'',pack:1,mrp:0,rate:0,gst:0,stock:0,pqty:1,freeQty:0,pdisc:0}));renderPurchase()}
function purchaseCalc(){let gross=0,itemDisc=0;const lines=purchaseRows.filter(r=>r.product||r.batch).map(r=>{const pack=Math.max(1,num(r.pack)||1),qty=Math.max(0,num(r.pqty)),free=Math.max(0,num(r.freeQty)),rate=num(r.prate??r.rate),base=qty*rate,disc=base*Math.min(100,Math.max(0,num(r.pdisc)))/100,taxable=Math.max(0,base-disc),gst=num(r.gst),tax=taxable*gst/100,total=taxable+tax;gross+=base;itemDisc+=disc;return {...r,pack,qty,free,prate:rate,pdisc:num(r.pdisc),base,itemDiscount:disc,taxable,tax,total,stockUnits:(qty+free)*pack}});const after=gross-itemDisc,billDisc=Math.min(after,Math.max(0,num($('pDiscount')?.value))),ratio=after?Math.max(0,(after-billDisc)/after):1,final=lines.map(r=>({...r,taxable2:r.taxable*ratio,tax2:r.tax*ratio,total2:r.taxable*ratio+r.tax*ratio})),tax=final.reduce((a,r)=>a+r.tax2,0),taxable=final.reduce((a,r)=>a+r.taxable2,0),round=num($('pRound')?.value),total=Math.max(0,taxable+tax+round),paid=Math.min(total,Math.max(0,num($('pPaid')?.value)));return{lines:final,gross,itemDisc,billDisc,taxable,tax,round,total,paid,balance:Math.max(0,total-paid)}}
function renderPurchase(){const body=$('pBody');if(!body)return;const c=purchaseCalc();body.innerHTML=c.lines.map((r,i)=>`<tr><td>${i+1}</td><td><input value="${esc(r.product)}" onchange="purchaseRows[${i}].product=this.value"></td><td><input value="${esc(r.batch)}" onchange="purchaseRows[${i}].batch=this.value"></td><td><input value="${esc(r.exp)}" placeholder="MM/YYYY" onchange="purchaseRows[${i}].exp=this.value"></td><td><input type="number" min="1" value="${r.pack}" onchange="purchaseRows[${i}].pack=this.value;renderPurchase()"></td><td><input type="number" min="0" value="${r.qty}" onchange="purchaseRows[${i}].pqty=this.value;renderPurchase()"></td><td><input type="number" min="0" value="${r.free}" onchange="purchaseRows[${i}].freeQty=this.value;renderPurchase()"></td><td><input type="number" min="0" max="100" step="0.01" value="${r.pdisc}" onchange="purchaseRows[${i}].pdisc=this.value;renderPurchase()"></td><td><input type="number" min="0" step="0.01" value="${r.prate}" onchange="purchaseRows[${i}].prate=this.value;renderPurchase()"></td><td><input type="number" min="0" step="0.01" value="${r.mrp}" onchange="purchaseRows[${i}].mrp=this.value;renderPurchase()"></td><td><select onchange="purchaseRows[${i}].gst=this.value;renderPurchase()">${GST.map(g=>`<option value="${g}" ${num(r.gst)===g?'selected':''}>${g}%</option>`).join('')}</select></td><td>${money(r.total2)}</td><td><button class="btn red" onclick="purchaseRows.splice(${i},1);renderPurchase()">×</button></td></tr>`).join('')||'<tr><td colspan="13" class="muted">No items. Search, create a batch, or use Blank Line.</td></tr>';const inter=$('pGst')?.value==='inter';$('pTotals').innerHTML=`<div class="totalbox"><div class="totalrow"><span>Gross Purchase</span><b>${money(c.gross)}</b></div><div class="totalrow"><span>Item Discount</span><b>${money(c.itemDisc)}</b></div><div class="totalrow"><span>Bill Discount</span><b>${money(c.billDisc)}</b></div><div class="totalrow"><span>Taxable</span><b>${money(c.taxable)}</b></div><div class="totalrow"><span>${inter?'IGST':'CGST + SGST'}</span><b>${money(c.tax)}</b></div><div class="totalrow"><span>Round Off</span><b>${money(c.round)}</b></div><div class="totalrow net"><span>GRAND TOTAL</span><b>${money(c.total)}</b></div><div class="totalrow"><span>Paid</span><b>${money(c.paid)}</b></div><div class="totalrow"><span>Balance</span><b>${money(c.balance)}</b></div><div class="actions"><button class="btn green" onclick="savePurchase()">💾 Save Purchase + Update Stock</button><button class="btn" onclick="previewPurchase()">🖨 Preview</button><button class="btn gray" onclick="newPurchase()">Clear</button></div></div>`}
function savePurchase(){const c=purchaseCalc(),supplier=$('pSupplier').value,invoice=$('pInvoice').value.trim();if(!supplier)return alert('Create/select supplier first.');if(!invoice)return alert('Invoice number required.');if(db.purchases.some(p=>String(p.no).toLowerCase()===invoice.toLowerCase()))return alert('This purchase invoice number already exists.');if(!c.lines.length)return alert('Add at least one item.');for(const r of c.lines){if(!r.product||!r.batch)return alert('Product and Batch required on every line.');if(r.qty<=0)return alert('Qty must be greater than 0: '+r.product);if(r.mrp<=0)return alert('MRP required: '+r.product);if(r.prate<0)return alert('Purchase rate invalid: '+r.product)}c.lines.forEach(r=>{let it=db.items.find(i=>i.product.toLowerCase()===r.product.toLowerCase()&&i.batch.toLowerCase()===r.batch.toLowerCase());if(it){it.stock=num(it.stock)+r.stockUnits;it.pack=r.pack;it.rate=r.prate;it.mrp=r.mrp;it.gst=r.gst;it.exp=r.exp||it.exp;it.company=r.company||it.company;it.salt=r.salt||it.salt;it.hsn=r.hsn||it.hsn}else db.items.push(normalizeItem({product:r.product,barcode:r.barcode,company:r.company,salt:r.salt,hsn:r.hsn,unit:r.unit,batch:r.batch,exp:r.exp,pack:r.pack,mrp:r.mrp,rate:r.prate,gst:r.gst,stock:r.stockUnits,rack:r.rack,reorder:r.reorder}))});const b={no:invoice,date:$('pDate').value,supplier,payment:$('pPay').value,mode:$('pGst').value,gross:c.gross,itemDiscount:c.itemDisc,billDiscount:c.billDisc,discount:c.itemDisc+c.billDisc,taxable:c.tax,tax:c.tax,round:c.round,total:c.total,paid:c.paid,balance:c.balance,lines:c.lines};b.taxable=c.taxable;db.purchases.push(b);save();alert('Purchase saved and stock updated: '+invoice);printPurchase(b)}
function party(){const customers=db.parties.filter(p=>p.type==='Customer'),suppliers=db.parties.filter(p=>p.type==='Supplier');$('app').innerHTML=layout('Party Master',`<button class="btn" onclick="partyModal('Customer','party')">+ Create Customer</button> <button class="btn" onclick="partyModal('Supplier','party')">+ Create Supplier</button>`)+`<div class="card"><h3>Customers / Suppliers</h3><div class="scroll"><table><tr><th>Name</th><th>Type</th><th>Mobile</th><th>GSTIN</th><th>Address</th><th>Credit Limit</th><th>Action</th></tr>${db.parties.map((p,i)=>`<tr><td>${esc(p.name)}</td><td>${p.type}</td><td>${esc(p.mobile)}</td><td>${esc(p.gstin||'-')}</td><td>${esc(p.address)}</td><td>${money(p.creditLimit)}</td><td><button class="btn gray" onclick="editParty(${i})">Edit</button> <button class="btn red" onclick="deleteParty(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No parties.</td></tr>'}</table></div></div>`}
function partyModal(type='Customer',ret='party',idx=null){modalReturn=ret;editingIndex=idx??-1;const p=idx==null?normalizeParty({type}):db.parties[idx];openModal(`${idx==null?'Create':'Edit'} ${type}`,`<div class="formgrid"><div class="field wide"><label>Name *</label><input id="mPName" autofocus value="${esc(p.name)}"></div><div class="field"><label>Type</label><select id="mPType"><option ${p.type==='Customer'?'selected':''}>Customer</option><option ${p.type==='Supplier'?'selected':''}>Supplier</option></select></div><div class="field"><label>Mobile</label><input id="mPMobile" value="${esc(p.mobile)}"></div><div class="field"><label>GSTIN</label><input id="mPGSTIN" value="${esc(p.gstin)}"></div><div class="field wide"><label>Address</label><input id="mPAddress" value="${esc(p.address)}"></div><div class="field"><label>Credit Limit ₹</label><input id="mPCredit" type="number" min="0" value="${p.creditLimit}"></div></div><div class="actions"><button class="btn green" onclick="saveParty(${idx==null?-1:idx})">Save Party</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`)}
function saveParty(idx){const name=$('mPName').value.trim(),type=$('mPType').value;if(!name)return alert('Party name required.');if(db.parties.some((p,i)=>i!==idx&&p.name.toLowerCase()===name.toLowerCase()&&p.type===type))return alert('Same party already exists.');const p=normalizeParty({name,type,mobile:$('mPMobile').value.trim(),gstin:$('mPGSTIN').value.trim(),address:$('mPAddress').value.trim(),creditLimit:num($('mPCredit').value)});if(idx<0)db.parties.push(p);else db.parties[idx]=p;save();closeModal();if(modalReturn==='sale'){sale();$('saleParty').value=name;fillParty('sale')}else if(modalReturn==='purchase'){purchase();$('pSupplier').value=name}else show(modalReturn||'party')}
function editParty(i){partyModal(db.parties[i]?.type||'Customer','party',i)}
function deleteParty(i){if(!confirm('Delete this party? Existing bills remain safe.'))return;db.parties.splice(i,1);save();party()}
function item(){const q=($('itemQ')?.value||'').toLowerCase();const rows=db.items.filter(i=>(i.product+' '+i.company+' '+i.salt+' '+i.barcode+' '+i.batch+' '+i.hsn).toLowerCase().includes(q));$('app').innerHTML=layout('Item Master',`<button class="btn" onclick="itemModal('item')">+ Create Item / Batch</button> <button class="btn gray" onclick="loadStarterCatalogue()">📚 Load Starter Catalogue</button>`)+`<div class="card"><h3>Medicine / Batch List</h3><input id="itemQ" placeholder="Search product / company / salt / barcode / batch" value="${esc(q)}" oninput="filterItems(this.value)"><div class="scroll" style="margin-top:10px"><table><tr><th>Product</th><th>Company</th><th>Salt</th><th>Barcode</th><th>Batch</th><th>Exp</th><th>Pack</th><th>MRP</th><th>Purchase Rate</th><th>GST</th><th>Stock</th><th>Rack</th><th>Action</th></tr>${rows.map((i,idx)=>`<tr><td><b>${esc(i.product)}</b></td><td>${esc(i.company)}</td><td>${esc(i.salt)}</td><td>${esc(i.barcode)}</td><td>${esc(i.batch)}</td><td>${esc(i.exp)}</td><td>${i.pack}</td><td>${money(i.mrp)}</td><td>${money(i.rate)}</td><td>${i.gst}%</td><td>${i.stock}</td><td>${esc(i.rack)}</td><td><button class="btn gray" onclick="editItem('${esc(i.id)}')">Edit</button> <button class="btn red" onclick="deleteItem('${esc(i.id)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="13">No items found.</td></tr>'}</table></div></div>`}
function filterItems(){item()}
function itemModal(ret='item',id=null){modalReturn=ret;const i=id?db.items.find(x=>x.id===id):normalizeItem({});editingIndex=id?db.items.findIndex(x=>x.id===id):-1;openModal(`${id?'Edit':'Create'} Medicine / Batch`,`<div class="actions"><button class="btn gray" type="button" onclick="catalogPicker()">📚 Select from Medicine Catalogue</button></div><div class="formgrid"><div class="field"><label>Product *</label><input id="mProduct" autofocus value="${esc(i.product)}"></div><div class="field"><label>Barcode</label><input id="mBarcode" value="${esc(i.barcode)}"></div><div class="field"><label>Company</label><input id="mCompany" value="${esc(i.company)}"></div><div class="field"><label>Salt / Composition</label><input id="mSalt" value="${esc(i.salt)}"></div><div class="field"><label>HSN / SAC</label><input id="mHSN" value="${esc(i.hsn)}"></div><div class="field"><label>Unit</label><select id="mUnit">${UNITS.map(u=>`<option ${i.unit===u?'selected':''}>${u}</option>`).join('')}</select></div><div class="field"><label>Batch *</label><input id="mBatch" value="${esc(i.batch)}"></div><div class="field"><label>Expiry MM/YYYY</label><input id="mExp" placeholder="12/2027" value="${esc(i.exp)}"></div><div class="field"><label>Pack (units/strip)</label><input id="mPack" type="number" min="1" value="${i.pack}"></div><div class="field"><label>MRP / Strip *</label><input id="mMRP" type="number" min="0" step="0.01" value="${i.mrp}"></div><div class="field"><label>Purchase Rate / Strip</label><input id="mRate" type="number" min="0" step="0.01" value="${i.rate}"></div><div class="field"><label>GST %</label><select id="mGST">${GST.map(g=>`<option value="${g}" ${num(i.gst)===g?'selected':''}>${g}%</option>`).join('')}</select></div><div class="field"><label>Opening Stock (units)</label><input id="mStock" type="number" min="0" value="${i.stock}"></div><div class="field"><label>Rack</label><input id="mRack" value="${esc(i.rack)}"></div><div class="field"><label>Reorder Level</label><input id="mReorder" type="number" min="0" value="${i.reorder}"></div></div><div class="actions"><button class="btn green" onclick="saveItem()">Save Item</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`)}

function catalogPicker(){
  openModal('Medicine Catalogue',`<div class="note"><b>Mega Catalogue:</b> Search the 251K+ medicine master by product, company or salt. Select a catalogue item to fill the Item Master form. Batch, expiry, MRP, purchase rate and opening stock remain for your store to enter.</div><div class="field"><label>Search medicine / salt / company</label><input id="catQ" autofocus placeholder="e.g. paracetamol, amoxicillin, azithromycin" oninput="renderCatalog(this.value)"></div><div id="catStatus" class="muted" style="margin-top:8px">Loading catalogue…</div><div id="catResults" class="scroll" style="margin-top:10px;max-height:55vh"></div>`);
  renderCatalog('');
}
function parseCSVLine(line){
  const out=[]; let cur='', quoted=false;
  for(let i=0;i<line.length;i++){
    const c=line[i];
    if(c==='"'){
      if(quoted && line[i+1]==='"'){cur+='"';i++;}
      else quoted=!quoted;
    }else if(c===',' && !quoted){out.push(cur);cur='';}
    else cur+=c;
  }
  out.push(cur); return out;
}
async function loadMegaCatalogue(){
  if(window.rishuMegaCatalog)return window.rishuMegaCatalog;
  if(window.rishuMegaLoading)return window.rishuMegaLoading;
  window.rishuMegaLoading=(async()=>{
    const files=['medicine_catalogue_part1.csv','medicine_catalogue_part2.csv','medicine_catalogue_part3.csv','medicine_catalogue_part4.csv'];
    const rows=[];
    for(const file of files){
      const r=await fetch('./'+file,{cache:'no-store'});
      if(!r.ok)throw new Error(file+' not found ('+r.status+').');
      const text=await r.text();
      const lines=text.split(/\r?\n/);
      if(!lines.length)continue;
      const header=parseCSVLine(lines[0]);
      const idx={}; header.forEach((h,i)=>idx[h.trim()]=i);
      for(let i=1;i<lines.length;i++){
        const line=lines[i]; if(!line.trim())continue;
        const a=parseCSVLine(line);
        const product=a[idx.product]||''; if(!product)continue;
        rows.push({product,company:a[idx.company]||'',salt:a[idx.salt]||'',dosage_form:a[idx.dosage_form]||'',pack:a[idx.pack]||'',reference_price:a[idx.reference_price]||'',discontinued:a[idx.discontinued]||''});
      }
    }
    window.rishuMegaCatalog=rows; return rows;
  })().catch(e=>{window.rishuMegaLoading=null;throw e;});
  return window.rishuMegaLoading;
}
async function renderCatalog(q=''){
  const box=$('catResults'),status=$('catStatus'); if(!box)return;
  q=String(q||'').trim().toLowerCase();
  try{
    if(status)status.textContent='Loading 251K+ catalogue…';
    const data=await loadMegaCatalogue();
    const terms=q.split(/\s+/).filter(Boolean);
    const rows=data.filter(x=>!terms.length||terms.every(t=>(x.product+' '+x.company+' '+x.salt+' '+x.dosage_form+' '+x.pack).toLowerCase().includes(t))).slice(0,50);
    if(status)status.textContent=`${data.length.toLocaleString('en-IN')} catalogue records loaded • showing ${rows.length}`;
    box.innerHTML=rows.map((x,n)=>`<div class="card" style="margin:8px 0;padding:12px"><b>${esc(x.product)}</b><div class="muted">${esc(x.salt||'')} • ${esc(x.company||'')} • ${esc(x.dosage_form||'')} • Pack ${esc(x.pack||'')}</div><button class="btn gray" type="button" onclick="selectCatalog(${n})">Select</button></div>`).join('')||'<div class="empty">No catalogue item found.</div>';
    window.rishuCatalogFiltered=rows;
  }catch(e){if(status)status.textContent='Catalogue load failed';box.innerHTML='<div class="danger">Could not load the mega catalogue: '+esc(e.message||'unknown error')+'</div>';}
}
function selectCatalog(n){
  const x=(window.rishuCatalogFiltered||[])[n]; if(!x)return;
  closeModal();
  itemModal(modalReturn, null);
  $('mProduct').value=x.product||''; $('mBarcode').value=x.barcode||''; $('mCompany').value=x.company||''; $('mSalt').value=x.salt||''; $('mHSN').value=x.hsn||''; $('mUnit').value=x.unit||'Tablet'; $('mPack').value=x.pack||1; $('mGST').value=x.gst??0;
  $('mBatch').focus();
}
function saveItem(){const product=$('mProduct').value.trim(),batch=$('mBatch').value.trim();if(!product||!batch)return alert('Product and Batch are required.');const id=editingIndex>=0?db.items[editingIndex].id:cryptoRandom(),i=normalizeItem({id,product,barcode:$('mBarcode').value.trim(),company:$('mCompany').value.trim(),salt:$('mSalt').value.trim(),hsn:$('mHSN').value.trim(),unit:$('mUnit').value,batch,exp:$('mExp').value.trim(),pack:num($('mPack').value)||1,mrp:num($('mMRP').value),rate:num($('mRate').value),gst:num($('mGST').value),stock:num($('mStock').value),rack:$('mRack').value.trim(),reorder:num($('mReorder').value)||10});if(db.items.some((x,j)=>j!==editingIndex&&x.product.toLowerCase()===product.toLowerCase()&&x.batch.toLowerCase()===batch.toLowerCase()))return alert('This Product + Batch already exists.');if(editingIndex<0)db.items.push(i);else db.items[editingIndex]=i;save();closeModal();if(modalReturn==='sale'){sale();saleRows.push({...i,stripQty:1,looseQty:0,discount:0});renderSale()}else if(modalReturn==='purchase'){purchase();purchaseRows.push({...i,pqty:1,freeQty:0,prate:i.rate,pdisc:0});renderPurchase()}else show(modalReturn||'item')}
function editItem(id){itemModal('item',id)}
function deleteItem(id){const i=db.items.findIndex(x=>x.id===id);if(i<0)return;if(!confirm('Delete this item/batch? Existing bills remain safe.'))return;db.items.splice(i,1);save();item()}
function stock(){const low=db.items.filter(i=>num(i.stock)<=num(i.reorder));$('app').innerHTML=layout('Stock',`<button class="btn" onclick="stockAdjustModal()">± Stock Adjustment</button>`)+`<div class="card"><h3>Batch-wise Stock</h3><input id="stockQ" placeholder="Search product / batch / rack" oninput="renderStock(this.value)"><div id="stockData"></div></div><div class="card"><h3>Low Stock</h3>${low.map(i=>`<div class="danger">⚠ ${esc(i.product)} • ${esc(i.batch)} • ${i.stock} units</div>`).join('')||'<div class="muted">No low-stock items.</div>'}</div>`;renderStock('')}
function renderStock(q){q=(q||'').toLowerCase();const rows=db.items.filter(i=>(i.product+' '+i.batch+' '+i.barcode+' '+i.rack).toLowerCase().includes(q));$('stockData').innerHTML=`<div class="scroll"><table><tr><th>Product</th><th>Batch</th><th>Expiry</th><th>Pack</th><th>Stock Units</th><th>Strips</th><th>MRP</th><th>Purchase Rate</th><th>GST</th><th>Rack</th></tr>${rows.map(i=>`<tr><td>${esc(i.product)}</td><td>${esc(i.batch)}</td><td>${esc(i.exp)}</td><td>${i.pack}</td><td><b>${i.stock}</b></td><td>${(num(i.stock)/Math.max(1,num(i.pack))).toFixed(2)}</td><td>${money(i.mrp)}</td><td>${money(i.rate)}</td><td>${i.gst}%</td><td>${esc(i.rack)}</td></tr>`).join('')||'<tr><td colspan="10">No stock.</td></tr>'}</table></div>`}
function stockAdjustModal(){openModal('Stock Adjustment',`<div class="formgrid"><div class="field wide"><label>Product / Batch *</label><select id="adjItem">${db.items.map(i=>`<option value="${esc(i.id)}">${esc(i.product)} • ${esc(i.batch)} • Stock ${i.stock}</option>`).join('')}</select></div><div class="field"><label>Adjustment Units</label><input id="adjQty" type="number" step="1" value="0"></div><div class="field wide"><label>Reason</label><input id="adjReason" placeholder="Damage / Opening correction / Physical count"></div></div><div class="actions"><button class="btn green" onclick="adjustStock()">Save Adjustment</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`)}
function adjustStock(){const it=db.items.find(i=>i.id===$('adjItem').value),q=Math.trunc(num($('adjQty').value));if(!it||!q)return alert('Enter valid adjustment.');if(num(it.stock)+q<0)return alert('Stock cannot go below zero.');it.stock+=q;save();closeModal();stock()}
function reports(){ $('app').innerHTML=layout('Reports')+`<div class="card"><div class="actions"><button class="btn" onclick="salesBook()">Sales Book</button><button class="btn gray" onclick="purchaseBook()">Purchase Book</button><button class="btn gray" onclick="dayBook()">Day Book</button><button class="btn gray" onclick="ledger()">Party Ledger</button><button class="btn gray" onclick="stockLedger()">Stock Ledger</button><button class="btn gray" onclick="expiryReport()">Expiry 6 Months</button><button class="btn gray" onclick="exportCSV('sales')">Export Sales</button><button class="btn gray" onclick="exportCSV('purchases')">Export Purchase</button><button class="btn gray" onclick="exportCSV('items')">Export Items</button><button class="btn gray" onclick="exportCSV('parties')">Export Parties</button></div></div><div id="reportArea" class="card"><h3>Choose a report</h3></div>`}
function salesTable(){return `<div class="scroll"><table><tr><th>Bill</th><th>Date</th><th>Party</th><th>Doctor</th><th>Taxable</th><th>GST</th><th>Net</th><th>Action</th></tr>${db.sales.map((s,i)=>`<tr><td>${esc(s.no)}</td><td>${esc(s.date)}</td><td>${esc(s.party)}</td><td>${esc(s.doctor||'-')}</td><td>${money(s.taxable)}</td><td>${money(s.tax)}</td><td><b>${money(s.net)}</b></td><td><button class="btn gray" onclick="printSale(db.sales[${i}])">🖨 Reprint</button> <button class="btn gray" onclick="shareWhatsApp(${i})">WhatsApp</button></td></tr>`).join('')||'<tr><td colspan="8">No sales.</td></tr>'}</table></div>`}
function purchaseTable(){return `<div class="scroll"><table><tr><th>Invoice</th><th>Date</th><th>Supplier</th><th>Taxable</th><th>GST</th><th>Total</th><th>Paid</th><th>Balance</th><th>Action</th></tr>${db.purchases.map((p,i)=>`<tr><td>${esc(p.no)}</td><td>${esc(p.date)}</td><td>${esc(p.supplier)}</td><td>${money(p.taxable)}</td><td>${money(p.tax)}</td><td><b>${money(p.total)}</b></td><td>${money(p.paid)}</td><td>${money(p.balance)}</td><td><button class="btn gray" onclick="printPurchase(db.purchases[${i}])">🖨 Reprint</button></td></tr>`).join('')||'<tr><td colspan="9">No purchases.</td></tr>'}</table></div>`}
function salesBook(){$('reportArea').innerHTML='<h3>Sales Book</h3>'+salesTable()}
function purchaseBook(){$('reportArea').innerHTML='<h3>Purchase Book</h3>'+purchaseTable()}
function dayBook(){const rows=[...db.sales.map(x=>({date:x.date,doc:x.no,type:'Sale',party:x.party,amount:x.net})),...db.purchases.map(x=>({date:x.date,doc:x.no,type:'Purchase',party:x.supplier,amount:x.total}))].sort((a,b)=>String(a.date).localeCompare(String(b.date)));$('reportArea').innerHTML=`<h3>Day Book</h3><div class="scroll"><table><tr><th>Date</th><th>Document</th><th>Type</th><th>Party</th><th>Amount</th></tr>${rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.doc)}</td><td>${r.type}</td><td>${esc(r.party)}</td><td>${money(r.amount)}</td></tr>`).join('')||'<tr><td colspan="5">No transactions.</td></tr>'}</table></div>`}
function ledger(){const names=[...new Set([...db.parties.map(p=>p.name),...db.sales.map(s=>s.party),...db.purchases.map(p=>p.supplier)])].filter(Boolean);$('reportArea').innerHTML=`<h3>Party Ledger</h3><select id="ledgerParty" style="width:100%;padding:11px" onchange="renderLedger()"><option value="">Select Party</option>${names.map(n=>`<option>${esc(n)}</option>`).join('')}</select><div id="ledgerData"></div>`}
function renderLedger(){const n=$('ledgerParty').value;if(!n)return;let bal=0;const rows=[...db.sales.filter(x=>x.party===n).map(x=>({date:x.date,doc:x.no,type:'Sale',debit:num(x.net),credit:0})),...db.purchases.filter(x=>x.supplier===n).map(x=>({date:x.date,doc:x.no,type:'Purchase',debit:0,credit:num(x.total)}))].sort((a,b)=>String(a.date).localeCompare(String(b.date)));$('ledgerData').innerHTML=`<div class="scroll"><table><tr><th>Date</th><th>Doc</th><th>Type</th><th>Debit</th><th>Credit</th><th>Balance</th></tr>${rows.map(r=>{bal+=r.debit-r.credit;return `<tr><td>${esc(r.date)}</td><td>${esc(r.doc)}</td><td>${r.type}</td><td>${money(r.debit)}</td><td>${money(r.credit)}</td><td>${money(bal)}</td></tr>`}).join('')||'<tr><td colspan="6">No transactions.</td></tr>'}</table></div>`}
function stockLedger(){ $('reportArea').innerHTML=`<h3>Stock Ledger</h3><div class="field"><label>Search</label><input oninput="renderStockLedger(this.value)"></div><div id="stockLedgerData"></div>`;renderStockLedger('')}
function renderStockLedger(q){q=(q||'').toLowerCase();const rows=db.items.filter(i=>(i.product+' '+i.batch+' '+i.barcode).toLowerCase().includes(q));$('stockLedgerData').innerHTML=`<div class="scroll"><table><tr><th>Product</th><th>Batch</th><th>Expiry</th><th>Units</th><th>Strips</th><th>MRP</th><th>Rack</th></tr>${rows.map(i=>`<tr><td>${esc(i.product)}</td><td>${esc(i.batch)}</td><td>${esc(i.exp)}</td><td>${i.stock}</td><td>${(num(i.stock)/Math.max(1,num(i.pack))).toFixed(2)}</td><td>${money(i.mrp)}</td><td>${esc(i.rack)}</td></tr>`).join('')||'<tr><td colspan="7">No stock.</td></tr>'}</table></div>`}
function nearExpiryCount(){const now=new Date(),lim=new Date(now.getFullYear(),now.getMonth()+6,1);return db.items.filter(i=>{const m=String(i.exp).match(/^(\d{1,2})[\/-](\d{4})$/);if(!m)return false;const d=new Date(+m[2],+m[1]-1,1);return d>=new Date(now.getFullYear(),now.getMonth(),1)&&d<=lim}).length}
function expiryReport(){const now=new Date(),lim=new Date(now.getFullYear(),now.getMonth()+6,1),rows=db.items.filter(i=>{const m=String(i.exp).match(/^(\d{1,2})[\/-](\d{4})$/);if(!m)return false;const d=new Date(+m[2],+m[1]-1,1);return d>=new Date(now.getFullYear(),now.getMonth(),1)&&d<=lim}).sort((a,b)=>String(a.exp).localeCompare(String(b.exp)));$('reportArea').innerHTML=`<h3>Expiry Report • Next 6 Months</h3><div class="scroll"><table><tr><th>Product</th><th>Batch</th><th>Expiry</th><th>Stock</th><th>MRP</th><th>Rack</th></tr>${rows.map(i=>`<tr><td>${esc(i.product)}</td><td>${esc(i.batch)}</td><td>${esc(i.exp)}</td><td>${i.stock}</td><td>${money(i.mrp)}</td><td>${esc(i.rack)}</td></tr>`).join('')||'<tr><td colspan="6">No near-expiry batches.</td></tr>'}</table></div>`}
function printSale(b){const s=shop(),cg=b.mode==='local'?b.tax/2:0,sg=cg,ig=b.mode==='inter'?b.tax:0,w=window.open('','_blank');if(!w)return alert('Allow pop-ups for printing.');w.document.write(printHtml('TAX INVOICE',b,s,`<th>Qty</th><th>MRP</th>`,x=>`<td>${x.qty}</td><td>${money(x.mrp)}</td>`,cg,sg,ig,false));w.document.close()}
function printPurchase(b){const s=shop(),cg=b.mode==='local'?b.tax/2:0,sg=cg,ig=b.mode==='inter'?b.tax:0,w=window.open('','_blank');if(!w)return alert('Allow pop-ups for printing.');w.document.write(printHtml('PURCHASE INVOICE',b,s,`<th>Qty</th><th>Free</th><th>Rate</th><th>MRP</th>`,x=>`<td>${x.qty}</td><td>${x.free||0}</td><td>${money(x.prate)}</td><td>${money(x.mrp)}</td>`,cg,sg,ig,true));w.document.close()}
function printHtml(title,b,s,head,cellsFn,cg,sg,ig,purchase=false){return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(b.no)}</title><style>body{font-family:Arial,sans-serif;color:#111;padding:24px;font-size:12px}h1{text-align:center;margin:0;font-size:22px}h3{text-align:center;margin:5px 0 14px}hr{border:0;border-top:1px solid #222}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #222;padding:6px}th{background:#eee}.r{text-align:right}.tot{width:46%;margin-left:auto;margin-top:10px}.row{display:flex;justify-content:space-between;padding:4px}.net{border-top:2px solid #111;font-weight:800;font-size:15px;padding-top:8px}.small{font-size:11px}</style></head><body><h1>${esc(s.name)}</h1><h3>${title}</h3><div style="text-align:center">Retail Pharmacy • GST • Batch • Strip/Loose<br>${esc(s.address)} • Mob. ${esc(s.mobile)}</div><hr><b>${purchase?'Invoice':'Bill'} No.:</b> ${esc(b.no)} &nbsp;&nbsp; <b>Date:</b> ${esc(b.date)} &nbsp;&nbsp; <b>${purchase?'Supplier':'Customer'}:</b> ${esc(purchase?b.supplier:b.party)}<br>${!purchase?`<b>Mobile:</b> ${esc(b.mobile||'-')} &nbsp; <b>Doctor:</b> ${esc(b.doctor||'-')} &nbsp; <b>Rx No.:</b> ${esc(b.rx||'-')}<br>`:''}<b>Payment:</b> ${esc(b.payment||'-')} &nbsp; <b>GST Mode:</b> ${b.mode==='inter'?'Interstate • IGST':'Local • CGST + SGST'}<table><tr><th>#</th><th>Product</th><th>Batch</th><th>Expiry</th>${head}<th>GST</th><th>Amount</th></tr>${(b.lines||[]).map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.product)}</td><td>${esc(x.batch)}</td><td>${esc(x.exp)}</td>${cellsFn(x)}<td>${x.gst}%</td><td class="r">${money(purchase?x.total2:(x.after+x.tax))}</td></tr>`).join('')}</table><div class="tot"><div class="row"><span>${purchase?'Gross Purchase':'Subtotal'}</span><span>${money(purchase?b.gross:b.subtotal)}</span></div><div class="row"><span>Discount</span><span>${money(b.discount)}</span></div><div class="row"><span>Taxable Value</span><span>${money(b.taxable)}</span></div><div class="row"><span>CGST</span><span>${money(cg)}</span></div><div class="row"><span>SGST</span><span>${money(sg)}</span></div><div class="row"><span>IGST</span><span>${money(ig)}</span></div>${purchase?`<div class="row"><span>Round Off</span><span>${money(b.round)}</span></div>`:''}<div class="row net"><span>NET PAYABLE</span><span>${money(b.net||b.total)}</span></div>${purchase?`<div class="row"><span>Paid</span><span>${money(b.paid)}</span></div><div class="row"><span>Balance</span><span>${money(b.balance)}</span></div>`:''}</div><p><b>Amount in Words:</b> ${esc(inWords(b.net||b.total))}</p><p class="small">Terms: Please check medicine, batch and expiry before leaving the counter.</p><p style="margin-top:55px;text-align:right">Authorized Signature</p><script>window.print()</script></body></html>`}
function inWords(n){n=Math.round(num(n));if(n===0)return 'Zero Rupees only';const o=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],t=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];const two=x=>x<20?o[x]:t[Math.floor(x/10)]+(x%10?' '+o[x%10]:'');let r='';if(n>=10000000){r+=two(Math.floor(n/10000000))+' Crore ';n%=10000000}if(n>=100000){r+=two(Math.floor(n/100000))+' Lakh ';n%=100000}if(n>=1000){r+=two(Math.floor(n/1000))+' Thousand ';n%=1000}if(n>=100){r+=o[Math.floor(n/100)]+' Hundred ';n%=100}if(n)r+=(r?'and ':'')+two(n)+' ';return r.trim()+' Rupees only'}
function previewSale(){const c=saleCalc();if(!c.lines.length)return alert('Add item first.');const temp={no:'PREVIEW',date:new Date().toLocaleString('en-IN'),party:$('saleParty').value||'Cash Customer',mobile:$('saleMobile').value,doctor:$('saleDoctor').value,rx:$('saleRx').value,payment:$('salePay').value,mode:$('saleGst').value,subtotal:c.subtotal,discount:c.itemDiscount+c.billDisc,taxable:c.taxable,tax:c.tax,net:c.net,lines:c.lines};printSale(temp)}
function previewPurchase(){const c=purchaseCalc();if(!c.lines.length)return alert('Add item first.');const temp={no:$('pInvoice').value||'PREVIEW',date:$('pDate').value,supplier:$('pSupplier').value||'-',payment:$('pPay').value,mode:$('pGst').value,gross:c.gross,discount:c.itemDisc+c.billDisc,taxable:c.taxable,tax:c.tax,round:c.round,total:c.total,paid:c.paid,balance:c.balance,lines:c.lines};printPurchase(temp)}
function shareWhatsApp(i){const b=db.sales[i],txt=`${shop().name}\nBill: ${b.no}\nCustomer: ${b.party}\n${(b.lines||[]).map((x,j)=>`${j+1}. ${x.product} • ${x.batch} • Qty ${x.qty} • ${money(x.mrp)}`).join('\n')}\nNET: ${money(b.net)}`;window.open('https://wa.me/?text='+encodeURIComponent(txt),'_blank')}

function doctorOpts(selected=''){return `<option value="">Select Doctor</option>`+db.doctors.map(d=>`<option value="${esc(d.name)}" ${d.name===selected?'selected':''}>${esc(d.name)}${d.specialization?' • '+esc(d.specialization):''}</option>`).join('')}
function doctors(){
  $('app').innerHTML=layout('Doctor Master',`<button class="btn" onclick="doctorModal()">+ New Doctor</button>`)+`<div class="card"><div class="field"><label>Search Doctor</label><input id="doctorFilter" placeholder="Name / specialization / mobile" oninput="renderDoctors()"></div></div><div class="card"><div class="scroll"><table><thead><tr><th>Doctor</th><th>Specialization</th><th>Mobile</th><th>Clinic</th><th>Reg. No.</th><th>Action</th></tr></thead><tbody id="doctorBody"></tbody></table></div></div>`;renderDoctors()
}
function renderDoctors(){const q=($('doctorFilter')?.value||'').toLowerCase();const rows=db.doctors.filter(d=>(d.name+' '+d.specialization+' '+d.mobile+' '+d.clinic+' '+d.reg).toLowerCase().includes(q));$('doctorBody').innerHTML=rows.map(d=>`<tr><td><b>${esc(d.name)}</b></td><td>${esc(d.specialization||'-')}</td><td>${esc(d.mobile||'-')}</td><td>${esc(d.clinic||'-')}</td><td>${esc(d.reg||'-')}</td><td><button class="btn gray" onclick="doctorModal('${esc(d.id)}')">Edit</button> <button class="btn red" onclick="deleteDoctor('${esc(d.id)}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No doctors.</td></tr>'}
function doctorModal(id=''){const d=db.doctors.find(x=>x.id===id)||{};openModal(id?'Edit Doctor':'New Doctor',`<div class="formgrid"><div class="field wide"><label>Doctor Name *</label><input id="dName" value="${esc(d.name)}" autofocus></div><div class="field"><label>Specialization</label><input id="dSpec" value="${esc(d.specialization)}"></div><div class="field"><label>Mobile</label><input id="dMobile" value="${esc(d.mobile)}"></div><div class="field wide"><label>Clinic / Hospital</label><input id="dClinic" value="${esc(d.clinic)}"></div><div class="field"><label>Registration No.</label><input id="dReg" value="${esc(d.reg)}"></div></div><div class="actions"><button class="btn" onclick="saveDoctor('${esc(id)}')">Save Doctor</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`) }
function saveDoctor(id=''){const name=$('dName').value.trim();if(!name)return alert('Doctor name required.');const obj={id:id||cryptoRandom(),name,specialization:$('dSpec').value.trim(),mobile:$('dMobile').value.trim(),clinic:$('dClinic').value.trim(),reg:$('dReg').value.trim()};const ix=db.doctors.findIndex(x=>x.id===id);if(ix>=0)db.doctors[ix]=obj;else db.doctors.push(obj);save();closeModal();doctors()}
function deleteDoctor(id){if(!confirm('Delete this doctor?'))return;db.doctors=db.doctors.filter(x=>x.id!==id);save();doctors()}
function expenses(){ $('app').innerHTML=layout('Expenses',`<button class="btn" onclick="expenseModal()">+ Add Expense</button>`)+`<div class="card"><div class="scroll"><table><thead><tr><th>Date</th><th>Category</th><th>Note</th><th>Amount</th><th>Action</th></tr></thead><tbody>${db.expenses.map((e,i)=>`<tr><td>${esc(e.date)}</td><td>${esc(e.category)}</td><td>${esc(e.note||'-')}</td><td>${money(e.amount)}</td><td><button class="btn red" onclick="deleteExpense(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="5">No expenses.</td></tr>'}</tbody></table></div></div>`}
function expenseModal(){openModal('Add Expense',`<div class="formgrid"><div class="field"><label>Date</label><input id="eDate" type="date" value="${today()}"></div><div class="field"><label>Category</label><select id="eCat"><option>Rent</option><option>Electricity</option><option>Salary</option><option>Transport</option><option>Miscellaneous</option></select></div><div class="field wide"><label>Note</label><input id="eNote"></div><div class="field"><label>Amount ₹ *</label><input id="eAmount" type="number" min="0" step="0.01"></div></div><div class="actions"><button class="btn" onclick="saveExpense()">Save Expense</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`)}
function saveExpense(){const amount=num($('eAmount').value);if(amount<=0)return alert('Enter valid amount.');db.expenses.push({id:cryptoRandom(),date:$('eDate').value,category:$('eCat').value,note:$('eNote').value.trim(),amount});save();closeModal();expenses()}
function deleteExpense(i){if(confirm('Delete expense?')){db.expenses.splice(i,1);save();expenses()}}
function smartInsights(){const low=db.items.filter(i=>num(i.stock)<=num(i.reorder));const exp=db.items.filter(i=>isNearExpiry(i,90));const dead=db.items.filter(i=>num(i.stock)>0&&!db.sales.some(s=>(s.lines||[]).some(l=>l.id===i.id))).slice(0,10);const sold=new Map();db.sales.forEach(s=>(s.lines||[]).forEach(l=>sold.set(l.id,(sold.get(l.id)||0)+num(l.qty))));const fast=db.items.map(i=>({...i,sold:sold.get(i.id)||0})).sort((a,b)=>b.sold-a.sold).slice(0,5);return {low,exp,dead,fast}}
function isNearExpiry(exp,days){const m=String(exp.exp||'').match(/^(\d{1,2})[\/-](\d{4})$/);if(!m)return false;const d=new Date(+m[2],+m[1]-1,1),lim=new Date();lim.setDate(lim.getDate()+days);return d>=new Date(new Date().getFullYear(),new Date().getMonth(),1)&&d<=lim}
function dashboardV10(){const d=today(),sales=db.sales.filter(x=>String(x.date||'').slice(0,10)===d),saleTotal=sales.reduce((a,x)=>a+num(x.net),0),purchaseTotal=db.purchases.filter(x=>String(x.date||'').slice(0,10)===d).reduce((a,x)=>a+num(x.total),0),expenseTotal=db.expenses.filter(x=>String(x.date||'').slice(0,10)===d).reduce((a,x)=>a+num(x.amount),0),ins=smartInsights();$('app').innerHTML=layout('Dashboard',`<button class="btn" onclick="show('sale')">F2 • New Sale</button>`)+`<div class="grid"><div class="stat"><small>Today's Sale</small><b>${money(saleTotal)}</b></div><div class="stat"><small>Today's Purchase</small><b>${money(purchaseTotal)}</b></div><div class="stat"><small>Today's Expenses</small><b>${money(expenseTotal)}</b></div><div class="stat"><small>Net Cash Movement</small><b>${money(saleTotal-purchaseTotal-expenseTotal)}</b></div></div><div class="grid"><div class="stat"><small>Items / Batches</small><b>${db.items.length}</b></div><div class="stat"><small>Low Stock</small><b>${ins.low.length}</b></div><div class="stat"><small>Expiry ≤ 90 Days</small><b>${ins.exp.length}</b></div><div class="stat"><small>Doctors</small><b>${db.doctors.length}</b></div></div><div class="grid"><div class="card"><h3>🤖 Smart Purchase Suggestions</h3>${ins.low.slice(0,12).map(x=>`<div class="alertrow">🛒 <b>${esc(x.product)}</b> • Batch ${esc(x.batch)} • Stock ${x.stock} • Reorder ${x.reorder}</div>`).join('')||'<div class="muted">No urgent purchase suggestions.</div>'}</div><div class="card"><h3>⏳ Expiry Watch</h3>${ins.exp.slice(0,12).map(x=>`<div class="danger">⚠ ${esc(x.product)} • ${esc(x.batch)} • Exp ${esc(x.exp)} • Stock ${x.stock}</div>`).join('')||'<div class="muted">No near-expiry batches.</div>'}</div></div><div class="card"><h3>🔥 Fast Moving Items</h3><div class="scroll"><table><tr><th>Product</th><th>Batch</th><th>Sold Units</th><th>Current Stock</th></tr>${ins.fast.map(x=>`<tr><td>${esc(x.product)}</td><td>${esc(x.batch)}</td><td>${x.sold}</td><td>${x.stock}</td></tr>`).join('')||'<tr><td colspan="4">No sales yet.</td></tr>'}</table></div></div><div class="card"><h3>Quick Menu</h3><div class="actions"><button class="btn" onclick="show('sale')">🧾 Retail Sale</button><button class="btn gray" onclick="show('purchase')">🛒 Purchase</button><button class="btn gray" onclick="show('item')">💊 Item Master</button><button class="btn gray" onclick="show('stock')">📦 Stock</button><button class="btn gray" onclick="show('doctors')">👨‍⚕️ Doctors</button><button class="btn gray" onclick="show('expenses')">💸 Expenses</button><button class="btn gray" onclick="show('reports')">📊 Reports</button><button class="btn gray" onclick="show('backup')">💾 Backup</button></div></div>`}

function can(role){const u=window.currentUser;return u&&(u.role==='Admin'||u.role===role||role==='Staff')}
function purchaseOrders(){if(!can('Staff'))return alert('Permission denied.');const rows=db.purchaseOrders||[];$('app').innerHTML=layout('Purchase Orders',`<button class="btn" onclick="purchaseOrderModal()">+ New Purchase Order</button>`)+`<div class="card"><div class="scroll"><table><thead><tr><th>PO No.</th><th>Date</th><th>Supplier</th><th>Items</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td>${esc(p.no)}</td><td>${esc(p.date)}</td><td>${esc(p.supplier)}</td><td>${p.lines?.length||0}</td><td>${money(p.total)}</td><td><span class="badge">${esc(p.status||'Open')}</span></td><td><button class="btn gray" onclick="printPO(${i})">Print</button> <button class="btn gray" onclick="deletePO(${i})">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No purchase orders.</td></tr>'}</tbody></table></div></div>`}
function purchaseOrderModal(){openModal('New Purchase Order',`<div class="formgrid"><div class="field"><label>Supplier</label><select id="poSupplier">${partyOpts('Supplier')}</select></div><div class="field"><label>Date</label><input id="poDate" type="date" value="${today()}"></div><div class="field wide"><label>Items (Product | Qty | Rate)</label><textarea id="poLines" rows="8" placeholder="Paracetamol 500 | 10 | 25\nAmoxicillin 500 | 5 | 80"></textarea></div><div class="field"><label>Status</label><select id="poStatus"><option>Open</option><option>Sent</option><option>Received</option><option>Cancelled</option></select></div></div><div class="actions"><button class="btn" onclick="savePO()">Save PO</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`)}
function savePO(){const supplier=$('poSupplier').value;if(!supplier)return alert('Select supplier.');const lines=($('poLines').value||'').split('\n').map(x=>x.split('|').map(v=>v.trim())).filter(x=>x[0]);const clean=lines.map(x=>({product:x[0],qty:num(x[1]),rate:num(x[2])})).filter(x=>x.product&&x.qty>0);if(!clean.length)return alert('Add at least one valid line.');const no='PO'+String(1001+(db.purchaseOrders?.length||0));const total=clean.reduce((a,x)=>a+x.qty*x.rate,0);db.purchaseOrders.push({id:cryptoRandom(),no,date:$('poDate').value,supplier,status:$('poStatus').value,lines:clean,total});save();closeModal();purchaseOrders()}
function deletePO(i){if(confirm('Delete purchase order?')){db.purchaseOrders.splice(i,1);save();purchaseOrders()}}
function printPO(i){const p=db.purchaseOrders[i],s=shop();printHtml(`<h1>${esc(s.name)}</h1><p>${esc(s.address)} • ${esc(s.mobile)}</p><h2>PURCHASE ORDER</h2><p><b>PO:</b> ${esc(p.no)} &nbsp; <b>Date:</b> ${esc(p.date)} &nbsp; <b>Supplier:</b> ${esc(p.supplier)}</p><table><tr><th>#</th><th>Product</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>${p.lines.map((l,j)=>`<tr><td>${j+1}</td><td>${esc(l.product)}</td><td>${l.qty}</td><td>${money(l.rate)}</td><td>${money(l.qty*l.rate)}</td></tr>`).join('')}</table><h3>Total: ${money(p.total)}</h3>`)}
function accounting(){const sales=db.sales.reduce((a,x)=>a+num(x.net),0),purch=db.purchases.reduce((a,x)=>a+num(x.total),0),exp=db.expenses.reduce((a,x)=>a+num(x.amount),0),cashSales=db.sales.filter(x=>x.payment!=='Credit').reduce((a,x)=>a+num(x.net),0),creditSales=db.sales.filter(x=>x.payment==='Credit').reduce((a,x)=>a+num(x.net),0),paidPurch=db.purchases.reduce((a,x)=>a+num(x.paid),0),duePurch=Math.max(0,purch-paidPurch),customerDue=Math.max(0,creditSales-(db.payments||[]).filter(x=>x.type==='Customer').reduce((a,x)=>a+num(x.amount),0));$('app').innerHTML=layout('Accounting & Ledger',`<button class="btn" onclick="paymentModal()">+ Receive / Pay</button>`)+`<div class="grid"><div class="stat"><small>Gross Sales</small><b>${money(sales)}</b></div><div class="stat"><small>Purchases</small><b>${money(purch)}</b></div><div class="stat"><small>Expenses</small><b>${money(exp)}</b></div><div class="stat"><small>Gross Movement</small><b>${money(sales-purch-exp)}</b></div></div><div class="grid"><div class="stat"><small>Cash/UPI Sales</small><b>${money(cashSales)}</b></div><div class="stat"><small>Customer Credit</small><b>${money(customerDue)}</b></div><div class="stat"><small>Supplier Payable</small><b>${money(duePurch)}</b></div><div class="stat"><small>Payments Entries</small><b>${(db.payments||[]).length}</b></div></div><div class="card"><h3>Recent Payments</h3><div class="scroll"><table><tr><th>Date</th><th>Type</th><th>Party</th><th>Mode</th><th>Amount</th><th>Note</th></tr>${(db.payments||[]).slice().reverse().slice(0,50).map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.type)}</td><td>${esc(x.party)}</td><td>${esc(x.mode)}</td><td>${money(x.amount)}</td><td>${esc(x.note)}</td></tr>`).join('')||'<tr><td colspan="6">No payments.</td></tr>'}</table></div></div>`}
function paymentModal(){openModal('Receive / Pay',`<div class="formgrid"><div class="field"><label>Type</label><select id="payType"><option>Customer</option><option>Supplier</option><option>Expense</option></select></div><div class="field"><label>Date</label><input id="payDate" type="date" value="${today()}"></div><div class="field"><label>Party</label><input id="payParty" placeholder="Customer/Supplier"></div><div class="field"><label>Mode</label><select id="payMode"><option>Cash</option><option>UPI</option><option>Bank</option><option>Card</option></select></div><div class="field"><label>Amount ₹</label><input id="payAmount" type="number" min="0" step="0.01"></div><div class="field wide"><label>Note</label><input id="payNote"></div></div><div class="actions"><button class="btn" onclick="savePayment()">Save Entry</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`)}
function savePayment(){const amount=num($('payAmount').value);if(amount<=0)return alert('Enter valid amount.');db.payments.push({id:cryptoRandom(),date:$('payDate').value,type:$('payType').value,party:$('payParty').value.trim(),mode:$('payMode').value,amount,note:$('payNote').value.trim()});save();closeModal();accounting()}
function users(){if(!can('Admin'))return alert('Admin only.');$('app').innerHTML=layout('Users & Permissions',`<button class="btn" onclick="userModal()">+ New User</button>`)+`<div class="card"><div class="scroll"><table><tr><th>Name</th><th>Username</th><th>Role</th><th>Status</th><th></th></tr>${db.users.map((u,i)=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${esc(u.role)}</td><td>${u.active?'Active':'Disabled'}</td><td>${u.username==='admin'?'':`<button class="btn gray" onclick="deleteUser(${i})">Delete</button>`}</td></tr>`).join('')}</table></div></div>`}
function userModal(){openModal('Create User',`<div class="formgrid"><div class="field"><label>Name</label><input id="uName"></div><div class="field"><label>Username</label><input id="uUsername"></div><div class="field"><label>Password</label><input id="uPassword" type="password"></div><div class="field"><label>Role</label><select id="uRole"><option>Admin</option><option>Manager</option><option>Staff</option></select></div></div><div class="actions"><button class="btn" onclick="saveUser()">Create</button><button class="btn gray" onclick="closeModal()">Cancel</button></div>`)}
function saveUser(){const username=$('uUsername').value.trim();if(!username||!$('uPassword').value)return alert('Username and password required.');if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return alert('Username already exists.');db.users.push({id:cryptoRandom(),name:$('uName').value.trim()||username,username,password:$('uPassword').value,role:$('uRole').value,active:true});save();closeModal();users()}
function deleteUser(i){if(confirm('Delete user?')){db.users.splice(i,1);save();users()}}
function login(){if(window.currentUser)return;const saved=sessionStorage.getItem('rishu_user');if(saved){try{const u=db.users.find(x=>x.username===saved);if(u&&u.active){window.currentUser=u;return}}catch{}}document.body.insertAdjacentHTML('afterbegin',`<div id="loginScreen" class="modal" style="display:flex"><div class="modalbox" style="max-width:420px"><div class="modalhead"><h2>🔐 Rishu ERP Login</h2></div><div class="field"><label>Username</label><input id="loginUser" value="admin" autocomplete="username"></div><div class="field"><label>Password</label><input id="loginPass" type="password" value="admin123" autocomplete="current-password"></div><div class="actions"><button class="btn" onclick="doLogin()">Login</button></div><p class="muted">First login: admin / admin123. Change credentials by creating users and deleting the default account when ready.</p></div></div>`)}
function doLogin(){const u=db.users.find(x=>x.username===$('loginUser').value.trim()&&x.password===$('loginPass').value&&x.active);if(!u)return alert('Invalid username/password.');window.currentUser=u;sessionStorage.setItem('rishu_user',u.username);$('loginScreen')?.remove();show('dashboard')}
function logout(){sessionStorage.removeItem('rishu_user');window.currentUser=null;location.reload()}
function backup(){$('app').innerHTML=layout('Backup & Restore')+`<div class="card"><h3>💾 Complete Data Protection</h3><p>Items, batches, parties, sales, purchases aur returns ka backup.</p><div class="actions"><button class="btn" onclick="downloadBackup()">⬇ Download Backup</button><button class="btn gray" onclick="$('restore').click()">⬆ Restore Backup</button><button class="btn gray" onclick="restoreAuto()">♻ Restore Auto Backup</button><input id="restore" type="file" accept=".json,application/json" hidden onchange="restoreFile(event)"></div></div><div class="grid">${[['Items',db.items.length],['Parties',db.parties.length],['Sales',db.sales.length],['Purchases',db.purchases.length]].map(x=>`<div class="stat"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}</div>`}
function downloadBackup(){download(`Rishu_Medical_Backup_${today()}.json`,JSON.stringify({app:'RISHU MEDICAL AND HEALTHCARE ERP',version:11,exportedAt:new Date().toISOString(),data:db},null,2),'application/json')}
function restoreFile(e){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result),d=norm(x.data||x);if(!confirm(`Restore backup?\nItems ${d.items.length}\nParties ${d.parties.length}\nSales ${d.sales.length}\nPurchases ${d.purchases.length}\nCurrent data will be replaced.`))return;db=d;save();alert('Backup restored.');location.reload()}catch{alert('Invalid backup file.')}};r.readAsText(f)}
function restoreAuto(){const x=raw('rishu_erp_auto_backup'),d=norm(x?.data||x);if(!d.items.length&&!d.parties.length&&!d.sales.length&&!d.purchases.length)return alert('Auto backup available nahi hai.');if(confirm('Auto backup restore karein? Current data replace hoga.')){db=d;save();location.reload()}}
function settings(){const s=shop();const c=window.cloudBridge?window.cloudBridge.status():{configured:false,signedIn:false,email:''};$('app').innerHTML=layout('Shop / System & Cloud Settings',`<button class="btn" onclick="saveSettings()">Save Settings</button>`)+`<div class="card"><div class="formgrid"><div class="field wide"><label>Shop Name</label><input id="sName" value="${esc(s.name)}"></div><div class="field"><label>Mobile</label><input id="sMobile" value="${esc(s.mobile)}"></div><div class="field wide"><label>Address</label><input id="sAddress" value="${esc(s.address)}"></div></div></div>`+`<div class="card"><h3>☁️ Cloud Sync (Supabase)</h3><div class="note">Connect this ERP to a Supabase project for multi-device cloud data. Use only the publishable key in the browser; never use a service-role/secret key.</div><div class="formgrid"><div class="field wide"><label>Supabase Project URL</label><input id="sbUrl" placeholder="https://xxxx.supabase.co" value="${esc(localStorage.getItem('rishu_sb_url')||'')}"></div><div class="field wide"><label>Supabase Publishable Key</label><input id="sbKey" placeholder="sb_publishable_..." value="${esc(localStorage.getItem('rishu_sb_key')||'')}"></div><div class="field"><label>Cloud Email</label><input id="sbEmail" type="email" placeholder="you@example.com" value="${esc(localStorage.getItem('rishu_sb_email')||'')}"></div><div class="field"><label>Cloud Password</label><input id="sbPass" type="password" placeholder="Enter password"></div></div><div class="actions"><button class="btn" onclick="cloudConnect()">Connect / Sign In</button><button class="btn gray" onclick="cloudSignUp()">Create Cloud Account</button><button class="btn gray" onclick="cloudPull()">⬇ Pull Cloud</button><button class="btn gray" onclick="cloudPush()">⬆ Push Local</button><button class="btn gray" onclick="cloudLogout()">Sign Out</button></div><div id="cloudStatus" class="muted">${c.configured?(c.signedIn?'🟢 Connected: '+esc(c.email):'🟡 Configured, not signed in'):'⚪ Cloud not configured yet'}</div></div>`}
async function cloudConnect(){if(!window.cloudBridge)return alert('Cloud module not loaded.');return window.cloudBridge.connect($('sbUrl').value.trim(),$('sbKey').value.trim(),$('sbEmail').value.trim(),$('sbPass').value)}
async function cloudSignUp(){if(!window.cloudBridge)return alert('Cloud module not loaded.');return window.cloudBridge.signUp($('sbUrl').value.trim(),$('sbKey').value.trim(),$('sbEmail').value.trim(),$('sbPass').value)}
async function cloudPull(){if(!window.cloudBridge)return alert('Cloud module not loaded.');const d=await window.cloudBridge.pull();if(d){db=norm(d);localStorage.setItem(KEY,JSON.stringify(db));alert('Cloud data loaded on this device.');show('dashboard')}}
async function cloudPush(){if(!window.cloudBridge)return alert('Cloud module not loaded.');await window.cloudBridge.push(db)}
async function cloudLogout(){if(window.cloudBridge){await window.cloudBridge.logout();settings()}}
function saveSettings(){localStorage.setItem('rishu_shop_name',$('sName').value.trim()||'RISHU MEDICAL AND HEALTHCARE');localStorage.setItem('rishu_shop_mobile',$('sMobile').value.trim());localStorage.setItem('rishu_shop_address',$('sAddress').value.trim());alert('Settings saved.');show('dashboard')}
function openModal(title,html){$('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="modalbox"><div class="modalhead"><h2>${esc(title)}</h2><button class="btn gray" onclick="closeModal()">✕</button></div>${html}</div></div>`;setTimeout(()=>$('modalRoot').querySelector('input[autofocus]')?.focus(),50)}
function closeModal(){$('modalRoot').innerHTML=''}
function exportCSV(kind){let rows=[],head=[],name=kind;if(kind==='sales'){head=['Bill','Date','Party','Product','Batch','Expiry','Qty','MRP','GST','Amount'];rows=db.sales.flatMap(s=>s.lines.map(l=>[s.no,s.date,s.party,l.product,l.batch,l.exp,l.qty,l.mrp,l.gst,l.after+l.tax]))}else if(kind==='purchases'){head=['Invoice','Date','Supplier','Product','Batch','Expiry','Qty','Free','Purchase Rate','MRP','GST','Total'];rows=db.purchases.flatMap(p=>p.lines.map(l=>[p.no,p.date,p.supplier,l.product,l.batch,l.exp,l.qty,l.free,l.prate,l.mrp,l.gst,l.total2]))}else if(kind==='items'){head=['Product','Company','Salt','Barcode','Batch','Expiry','Pack','MRP','Purchase Rate','GST','Stock','Rack'];rows=db.items.map(i=>[i.product,i.company,i.salt,i.barcode,i.batch,i.exp,i.pack,i.mrp,i.rate,i.gst,i.stock,i.rack])}else{head=['Name','Type','Mobile','GSTIN','Address','Credit Limit'];rows=db.parties.map(p=>[p.name,p.type,p.mobile,p.gstin,p.address,p.creditLimit])}const csv=[head,...rows].map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');download(`Rishu_${name}_${today()}.csv`,csv,'text/csv')}
function download(name,data,type){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
const pages={dashboard:dashboardV10,sale,purchase,party,item,stock,reports,backup,settings,doctors,expenses,purchaseOrders,accounting,users};
Object.assign(window,{show,login,doLogin,logout,catalogPicker,renderCatalog,selectCatalog,purchaseOrders,purchaseOrderModal,savePO,deletePO,printPO,accounting,paymentModal,savePayment,users,userModal,saveUser,deleteUser,partyModal,doctorModal,saveDoctor,deleteDoctor,renderDoctors,expenseModal,saveExpense,deleteExpense,saveParty,editParty,deleteParty,itemModal,saveItem,editItem,deleteItem,filterItems,addSaleSearch,chooseItem,suggest,renderSale,saveSale,previewSale,newSale,newPurchase,addPurchaseSearch,addBlankPurchase,renderPurchase,savePurchase,previewPurchase,printSale,printPurchase,stockAdjustModal,adjustStock,salesBook,purchaseBook,dayBook,ledger,renderLedger,stockLedger,renderStockLedger,expiryReport,shareWhatsApp,exportCSV,backup,downloadBackup,restoreFile,restoreAuto,settings,saveSettings,closeModal,db,purchaseRows,saleRows,cloudConnect,cloudSignUp,cloudPull,cloudPush,cloudLogout});
window.normalizeItem=normalizeItem;window.saveERP=save;
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='F2'){e.preventDefault();show('sale')}if(e.key==='F3'){e.preventDefault();show('item')}if(e.key==='F4'){e.preventDefault();show('party')}if(e.key==='F8'){e.preventDefault();show('purchase')}});
save();login();if(window.currentUser)show('dashboard');
})();